modified eligibility condition
alma/alma-widgets pull request #10
Opened 2021-09-27 18:05 UTC by xenosnikos

2021-09-28 15:09 UTC, syjust requested changes

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +      if(plan.minAmount != 0){
indent and add spaces between `if` `(` and `{` here please

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +        }else{
indent and add spaces between `if` `(` and `{` here please

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +      else {
please, don't jump line for `else` statement

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +}
leave `\n` at EOF please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-28 15:09 UTC, syjust commented on src/widgets/PaymentPlans/PaymentPlans.tsx
> +​
remove line please (modify only part of code you have to)

2021-09-29 21:14 UTC, xenosnikos commented
@syjust  i think i covered all the formatting issues, i will be careful with this in future. 
let me know if i broke something :S

2021-09-30 14:28 UTC, closed without merging